name:                ud2drs
version:             0.1.0.0
license:             BSD3
author:              "Dag Haug"
maintainer:          "daghaug@uio.no"
copyright:           "2021 Dag Haug"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.uio.no/Universal-NLU/ud2drs#readme>

dependencies:
- base >= 4.7 && < 5
- text
- containers
- MissingH
- bytestring
- split
- regex-compat
- regex-tdfa
- parallel

library:
  source-dirs: src

executables:
  ud2drs-exe:
    main:                Main.hs
    source-dirs:         app/ud2drs
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - ud2drs
